# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3\

      v2
                  - name: Collect changelog of rush
  # You may pin to the exact commit or the version.
  # uses: xile611/collect-rush-changlog@4b29ccd1dbc15735137841e8476e597720aa19da
  uses: xile611/collect-rush-changlog@v1.1.0
  with:
    # The version of changelog, if not specified, the lastest changelog will be collected
    version: # optional
    # The root path of a rush project
    rush_path: # optional, default is ./
    # The black list of packageName, use comma to join multi package name
    black_list: # optional
    # The tags of packages, use comma to join multi package tag
    tags: # optional
          

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
